### ISSUE TITLE
Deobfuscate Pyarmor?

### ISSUE THREAD

**Issue by JokersCat** [6nz/Decompiled-and-Deobfuscated-stuff#1]
Can you deobfuscate pyarmor? And when yes how?

**Comment by 6nz** [comment]
easily 🥱

**Comment by JokersCat** [comment]
Oh nice how I bought a tool a while ago it is protected with pyarmor it wouldn’t be a problem for me but the thing is they closed thier project and took the auth. down so now I can’t login. Maybe you can show me how to crack it so I can use the tool again? 😅
